"""
Django settings for totp_management project.

Generated by 'django-admin startproject' using Django 5.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import warnings
from pathlib import Path
from dotenv import load_dotenv
from mongoengine import connect
from cryptography.utils import CryptographyDeprecationWarning

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the custom .env file
env_file_path = BASE_DIR / '.env.mongodb.django'
env_database_file_path = BASE_DIR / '.env.mongodb.db_store'
env_azure_file_path = BASE_DIR / '.env.azure.credentials'
env_api_file_path = BASE_DIR / '.env.api_keys'
env_acc_file_path = BASE_DIR / '.env.api.acc'

# Load Django environment variables
if os.path.exists(env_file_path):
    load_dotenv(env_file_path)
else:
    print(f"Environment file {env_file_path} does not exist")

# Load database environment variables
if os.path.exists(env_database_file_path):
    load_dotenv(env_database_file_path)
else:
    print(f"Database environment file {env_database_file_path} does not exist")

# Load Azure credentials environment variables
if os.path.exists(env_azure_file_path):
    load_dotenv(env_azure_file_path)
else:
    print(f"Azure credentials environment file {env_azure_file_path} does not exist")

# Load valid API keys.
if os.path.exists(env_api_file_path):
    load_dotenv(env_api_file_path)
else:
    print(f'API keys environment file {env_api_file_path} does not exist')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("No DJANGO_SECRET_KEY set for Django application")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False') == 'False'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '[::1]',  # This is the IPv6 localhost
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'mongoengine',
    'rest_framework',
    'django_celery_beat',
    'channels',
    'totp_services',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'totp_services.middleware.APIKeyMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'https://127.0.0.1:3000',
    'http://localhost',
    'https://localhost:3000',
]

CORS_ALLOW_HEADERS = [
    'X-API-KEY',
    'M-API-KEY',
    'Authorization',
    'Content-Type',
]

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'OPTIONS',
]

ROOT_URLCONF = 'totp_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'totp_management.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# MongoDB URIs
MONGO_DB_URI = os.getenv('MONGO_DB_URI')

# MongoDB Database Name
MONGO_DB_NAME_VERIFICATION = os.getenv('MONGO_DB_NAME_VERIFICATION')

# MongoDB Connection for the otp_management_database (verification-management)
try:
    connect(
        db=os.getenv('MONGO_DB_NAME_VERIFICATION'),
        host=os.getenv('MONGO_DB_URI'),
        alias="verification_db",  # Alias for the verification database
        connectTimeoutMS=5000,
        socketTimeoutMS=5000,
        serverSelectionTimeoutMS=5000
    )
except Exception as e:
    print(f"Failed to connect to MongoDB (verification). Error: {e}")
    raise

try:
    connect (
        db = os.getenv('USER_PROFILE_DB'),
        host = os.getenv('MONGO_DB_URI'),
        alias = 'user_profile_db',
        connectTimeoutMS = 5000,
        socketTimeoutMS = 5000,
        serverSelectionTimeoutMS = 5000
    )
except Exception as e:
    print(f'Failed to connect to MongoDB (user_profile). Error: {e}')
    raise

'''
# Celery Configurations
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
'''
'''
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'IGNORE_EXCEPTIONS': True,
        },
        'TIMEOUT': 300,
    }
}
'''
# Suppress CryptographyDeprecationWarning warnings
warnings.filterwarnings("ignore", category=CryptographyDeprecationWarning)

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'ignore_deprecation_warnings': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': lambda record: not isinstance(record.exc_info, tuple) or not issubclass(record.exc_info[0], CryptographyDeprecationWarning),
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'django.log'),
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'mobile_number': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'azure': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',  # Change this to WARNING or ERROR
            'propagate': False,
        },
        'azure.core': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',  # Change this to WARNING or ERROR
            'propagate': False,
        },
        'azure.identity': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',  # Change this to WARNING or ERROR
            'propagate': False,
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
'''
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
'''

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
